[theme]
# base                     = "dark"
primaryColor             = "#00387b"
backgroundColor          = "#F7F7F7"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#0F0F0F"
font                     = "sans serif"

#[server]
#headless = true
#address  = "0.0.0.0"
#port     = 6008

[browser]
gatherUsageStats = false
